[custom]
; ===== 策略组 =====
custom_proxy_group=🚀 节点选择`select`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 全球拦截`select`[]REJECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]🛑 全球拦截

; ===== 后端生成指令 =====
enable_rule_generator=false
overwrite_original_rules=true
