[custom]
; ===== 策略组 =====
custom_proxy_group=🚀 节点选择`select`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT

; ===== 规则集 =====
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🚀 节点选择,[]FINAL

; ===== 后端生成指令 =====
enable_rule_generator=true
overwrite_original_rules=true
